/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package leoninoide;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author rudarobson
 */
public class CreateProjectPopUp extends JDialog implements KeyListener, Runnable {

    private String pathSelected = null;

    @Override
    public void run() {
        this.showDialog();
    }

    /**
     * Creates new form CreateProjectPopUp
     */
    public CreateProjectPopUp() {
        initComponents();
        projectNameText.addKeyListener(this);
        //filePath.addKeyListener(this);
    }

    public void showDialog() {
        setModalityType(ModalityType.APPLICATION_MODAL);
        setSize(new Dimension(700, 200));
        setVisible(true);
    }

    public String getProjectName() {
        return projectNameText.getText();
    }

    public String getFolder() {
        return new File(filePath.getText()).getParent();
    }

    public String getFullPath() {
        return filePath.getText();
    }

    public void closeDialog() {
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selectFileBtn = new javax.swing.JButton();
        projectNameText = new javax.swing.JTextField();
        filePath = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setText("Name:");
        add(jLabel1);
        jLabel1.setBounds(30, 10, 50, 28);

        selectFileBtn.setText("Browse");
        selectFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileBtnActionPerformed(evt);
            }
        });
        add(selectFileBtn);
        selectFileBtn.setBounds(490, 60, 80, 30);
        add(projectNameText);
        projectNameText.setBounds(80, 10, 400, 30);
        add(filePath);
        filePath.setBounds(80, 60, 400, 30);

        jLabel2.setText("Folder:");
        add(jLabel2);
        jLabel2.setBounds(30, 60, 60, 28);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        add(okButton);
        okButton.setBounds(90, 100, 73, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void selectFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileBtnActionPerformed
        JFileChooser dlg = new JFileChooser();
        dlg.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        dlg.showOpenDialog(null);

        File f = dlg.getSelectedFile();

        pathSelected = f.getAbsolutePath() + "\\";
        filePath.setText(pathSelected + projectNameText.getText());


    }//GEN-LAST:event_selectFileBtnActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.closeDialog();

    }//GEN-LAST:event_okButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filePath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField projectNameText;
    private javax.swing.JButton selectFileBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
        if (e.getSource() == projectNameText) {
            filePath.setText(pathSelected + projectNameText.getText());
        }
    }
}
